### ISSUE TITLE
Ad Blockers Blocking PostHog Integration in Docusaurus Site

### ISSUE THREAD

**Issue by mrpmohiburrahman** [PostHog/posthog-docusaurus#16]
Hi,
I am trying to integrate PostHog into my Docusaurus [site](https://mrpmohiburrahman.github.io/awesome-react-native-ui/), but I am encountering an issue where the requests to PostHog are being blocked by ad blockers.

**Docusaurus Configuration:**

```
  plugins: [
    [
      "posthog-docusaurus",
      {
        apiKey: "my_api_key",
        appUrl: "https://us.i.posthog.com",
        enableInDevelopment: true,
        onPostHogReady: () => {
          console.log("PostHog is ready");
        },
      },
    ],
  ],

```

**Error:**
When the site is loaded, I receive the following console log message:
```
GET https://us.i.posthog.com/static/array.js net::ERR_BLOCKED_BY_CLIENT
```
![image](https://github.com/PostHog/posthog-docusaurus/assets/35300157/c4bade12-779e-4cf4-888f-b88ab4706701)

I understand that using a reverse proxy can mitigate this issue, as described in this [PostHog article](https://posthog.com/docs/advanced/proxy). However, setting up a reverse proxy is currently beyond my skill level.

**Question:**
Is there an alternative solution to prevent ad blockers from blocking PostHog on my site, other than setting up a reverse proxy?

**Comment by robbie-c** [comment]
There isn't really a good alternative, but we recently launched a [Managed reverse proxy](https://posthog.com/docs/advanced/proxy/managed-reverse-proxy) product which is much easier to set up than a traditional reverse proxy.

**Comment by rafaeelaudibert** [comment]
Closing this as we've been testing managed reverse proxies and they are a good solution for this, most of the time.
